### PR TITLE
Add permissions for viewing/downloading MARCXML, fix to MODS2MARC XSL

### PR DESCRIPTION
**Pull request by mjsuhonos**
Small fixes useful for typical installs.

### CODE REVIEW

**Comment by willtp87** [comment]
Just saw this in passing and had some concerns.  In general we don't permission links to individual datastreams in this fashion and these changes are backwards breaking; also the XSLT is from upstream and there was a decision to not change such things as can be seen in the history for that file.  I suggest implementing these changes in another module if you require them.  It may also be good to make this module accept custom XSLTs or implement a general datastream to datastream transform module.

**Comment by mjsuhonos** [comment]
Thanks for taking the time to comment and express your concerns, William.  Our intent is only to bring additional functionality into the module, not add more complexity or maintenance overhead for you.  The changes to implement permissions were based on existing code in the islandora_premis module (https://github.com/Islandora/islandora_premis/blob/7.x/islandora_premis.module#L47-L58) and the changes to the XSLT address a wide-ranging deficiency in the LC mapping which was last updated 10 years ago, so I think we can consider that upstream dead.

If you're uncomfortable with merging this PR, I'm happy to close it, and we will just maintain our own forks of the Islandora modules that we've been improving as we go forward.  Not a problem.

**Comment by willtp87** [comment]
Contributions are a good thing. I'd rather not see work lost from upstream.  If there is consensus on the permissions changes an update hook can keep things from being breaking.  If the LC mapping is really dead perhaps the roadmap guys will change their minds.

**Comment by mjsuhonos** [comment]
OK, great. I'm going to close this PR pending some further discussion in the forum and the roadmap committee.  If things change, I'll re-open it with details.

**Pull request closed without merging**
